apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citizens.fullname" . }}-kafka
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: kafka
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:{{ .Values.kafka.service.clientPort }},CONTROLLER://:{{ .Values.kafka.service.controllerPort }}"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:{{ .Values.kafka.service.clientPort }}"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka:{{ .Values.kafka.service.controllerPort }}"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: {{ .Values.kafka.env.clusterId | quote }}
          ports:
            - containerPort: {{ .Values.kafka.service.clientPort }}
              name: kafka
            - containerPort: {{ .Values.kafka.service.controllerPort }}
              name: controller
          {{- with .Values.resources.kafka }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
