{{- if .Values.kafkaUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUI.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{ .Values.kafkaUI.env.bootstrapServers | quote }}
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: {{ .Values.kafkaUI.env.zookeeperConnect | quote }}
          ports:
            - containerPort: {{ .Values.kafkaUI.service.port }}
              name: http
{{- end }}
