{{- $baseName := .Release.Name -}}
{{- $knative := .Values.knative | default dict -}}
{{- $serviceVals := $knative.service | default dict -}}
{{- $imageVals := $serviceVals.image | default dict -}}
{{- $imageRepo := default .Values.quarkusApp.image.repository $imageVals.repository -}}
{{- $imageTag := default .Values.quarkusApp.image.tag $imageVals.tag -}}
{{- $imagePullPolicy := default .Values.imagePullPolicy $imageVals.pullPolicy -}}
{{- $serviceName := default (printf "%s-funqy" $baseName) $serviceVals.name -}}
{{- $containerPort := default 8080 $serviceVals.containerPort -}}
{{- $serviceAnnotations := $serviceVals.annotations | default dict -}}
{{- $templateAnnotations := $serviceVals.templateAnnotations | default dict -}}
{{- $serviceLabels := $serviceVals.labels | default dict -}}
{{- $quarkusEnv := .Values.quarkusApp.env | default dict -}}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "citizens.labels" . | nindent 4 }}
    app.kubernetes.io/component: funqy
    {{- with $serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if $serviceAnnotations }}
  annotations:
    {{- toYaml $serviceAnnotations | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: funqy
      {{- if $templateAnnotations }}
      annotations:
        {{- toYaml $templateAnnotations | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: funqy-runtime
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          {{- if $imagePullPolicy }}
          imagePullPolicy: {{ $imagePullPolicy }}
          {{- end }}
          ports:
            - containerPort: {{ $containerPort }}
          env:
            - name: CAMEL_COMPONENT_KAFKA_BROKERS
              value: {{ $quarkusEnv.kafkaBootstrap | default "kafka:9092" | quote }}
            - name: MINIO_ENDPOINT
              value: {{ $quarkusEnv.minioEndpoint | default "http://minio:9000" | quote }}
            {{- if $quarkusEnv.awsAccessKeySecret }}
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.awsAccessKeySecret }}
                  key: bucket
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.awsAccessKeySecret }}
                  key: region
            - name: AWS_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.awsAccessKeySecret }}
                  key: accessKey
            - name: AWS_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.awsAccessKeySecret }}
                  key: secretKey
            {{- else }}
            - name: AWS_S3_BUCKET
              value: ""
            - name: AWS_S3_REGION
              value: ""
            - name: AWS_S3_ACCESSKEY
              value: ""
            - name: AWS_S3_SECRETKEY
              value: ""
            {{- end }}
            {{- if $quarkusEnv.minioCredsSecret }}
            - name: MINIO_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.minioCredsSecret }}
                  key: accessKey
            - name: MINIO_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.minioCredsSecret }}
                  key: secretKey
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ $quarkusEnv.minioCredsSecret }}
                  key: bucket
            {{- else }}
            - name: MINIO_ACCESSKEY
              value: ""
            - name: MINIO_SECRETKEY
              value: ""
            - name: MINIO_BUCKET
              value: ""
            {{- end }}
            {{- range $key, $val := $serviceVals.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- with $serviceVals.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
