apiVersion: v1
kind: Service
metadata:
  name: {{ include "citizens.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: quarkus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: quarkus
  ports:
    - port: {{ .Values.quarkusApp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
