imagePullPolicy: IfNotPresent

global:
  namespace: ""
  clusterDomain: "apps"

quarkusApp:
  image:
    repository: image-registry.openshift-image-registry.svc:5000/citizens-demo/citizens-demo-camel-s3-serverless
    tag: latest
  replicaCount: 1
  service:
    port: 8080
  route:
    enabled: true
    host: ""
    tls:
      termination: edge
      insecurePolicy: Redirect
  env:
    kafkaBootstrap: "kafka:9092"
    minioEndpoint: "http://minio:9000"
    awsAccessKeySecret: citizens-demo-aws
    awsSecretKeySecret: citizens-demo-aws
    minioCredsSecret: citizens-demo-minio
    knativeBrokerUrl: "broker-ingress.knative-eventing.svc.cluster.local/citizens-demo/citizens-demo-broker"

kafka:
  image: docker.io/bitnamilegacy/kafka:3.7.0-debian-12-r2
  replicaCount: 1
  service:
    clientPort: 9092
    controllerPort: 9093
  env:
    clusterId: "4L6g3nShT-eMCtK--X86sw"

minio:
  image: minio/minio:latest
  service:
    apiPort: 9000
    consolePort: 9001
  route:
    enabled: true
    consoleHost: ""
    apiHost: ""
    tls:
      termination: edge
      insecurePolicy: Redirect
  credsSecret: citizens-demo-minio
  persistence:
    enabled: false
    size: 10Gi

kafkaUI:
  enabled: true
  image: provectuslabs/kafka-ui:latest
  service:
    port: 8080
  route:
    enabled: true
    host: ""
    tls:
      termination: edge
      insecurePolicy: Redirect
  env:
    bootstrapServers: "kafka:9092"
    zookeeperConnect: "zookeeper:2181"

knative:
  broker:
    name: ""
    annotations: {}
    spec: {}
  trigger:
    name: ""
    brokerName: ""
    filterAttributes:
      type: "com.redhat.citizens.funqy.reversal"
      source: "citizens-demo.camel.funqy"
    subscriber:
      ref:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
      uri: ""
  service:
    name: ""
    image:
      repository: ""
      tag: ""
      pullPolicy: ""
    containerPort: 8080
    env: {}
    annotations: {}
    templateAnnotations: {}
    labels: {}
    resources: {}

resources:
  quarkusApp: {}
  kafka: {}
  minio: {}
  kafkaUI: {}

persistence:
  kafka: { enabled: false, size: 10Gi }
  minio: { enabled: false, size: 10Gi }
